// Generates a portable brand-kit CSS file from the wizard state.
import { mix, lighten, darken, isDark, readableOn, contrast } from "./utils.js";

const RADIUS_MAP = {
  sharp:   { sm: "0px",  md: "0px",  lg: "0px",  pill: "0px"  },
  soft:    { sm: "4px",  md: "6px",  lg: "10px", pill: "999px" },
  rounded: { sm: "8px",  md: "14px", lg: "22px", pill: "999px" },
  pill:    { sm: "16px", md: "24px", lg: "36px", pill: "999px" }
};

const DENSITY_MAP = {
  compact:     { ratio: 0.85, line: 1.5  },
  comfortable: { ratio: 1.0,  line: 1.65 },
  spacious:    { ratio: 1.2,  line: 1.75 }
};

const SPACING_BASE = [4, 8, 12, 16, 20, 24, 32, 40, 56, 72]; // px

export function generateBrandCss(brand, publisher) {
  const { colors: c, typography: t, tokens: tk } = brand;
  const radii = RADIUS_MAP[tk.radius] || RADIUS_MAP.rounded;
  const density = DENSITY_MAP[tk.density] || DENSITY_MAP.comfortable;
  const dark = tk.mood === "dark";

  // Derive surface & ink defaults if user picked a non-traditional combo.
  const surface = c.surface;
  const ink = c.ink;
  const muted = mix(ink, surface, 0.4);
  const subtle = mix(ink, surface, 0.85);
  const line   = mix(ink, surface, 0.88);
  const lineStrong = mix(ink, surface, 0.78);

  const onPrimary = readableOn(c.primary);
  const onAccent = readableOn(c.accent);
  const primarySoft = mix(c.primary, surface, 0.85);
  const accentSoft = mix(c.accent, surface, 0.88);

  const heading = `'${t.heading}', ${t.headingFallback}`;
  const body = `'${t.body}', ${t.bodyFallback}`;

  const space = SPACING_BASE.map((v) => `${(v * density.ratio).toFixed(2)}px`);

  const dark_ = dark
    ? `\n.bk-theme-dark { color-scheme: dark; }\n`
    : "";

  return `/*
 * Brand Kit — ${publisher.name || publisher.domain}
 * Generated by Brand Kit Studio
 * Source: ${publisher.url}
 *
 * Drop this file into your publisher template and apply the .bk-theme class
 * to the root container (or <body>) to opt into the brand kit.
 */

@import url("https://fonts.googleapis.com/css2?family=${encodeURIComponent(t.heading).replace(/%20/g, "+")}:wght@600;700;800&family=${encodeURIComponent(t.body).replace(/%20/g, "+")}:wght@400;500;600;700&display=swap");

.bk-theme {
  /* ---------- Color tokens ---------- */
  --bk-color-primary: ${c.primary};
  --bk-color-primary-soft: ${primarySoft};
  --bk-color-primary-strong: ${darken(c.primary, 0.08)};
  --bk-color-on-primary: ${onPrimary};

  --bk-color-accent: ${c.accent};
  --bk-color-accent-soft: ${accentSoft};
  --bk-color-on-accent: ${onAccent};

  --bk-color-ink: ${ink};
  --bk-color-ink-muted: ${muted};
  --bk-color-ink-subtle: ${mix(ink, surface, 0.55)};

  --bk-color-surface: ${surface};
  --bk-color-surface-1: ${dark ? lighten(surface, 0.04) : darken(surface, 0.02)};
  --bk-color-surface-2: ${dark ? lighten(surface, 0.08) : darken(surface, 0.05)};

  --bk-color-line: ${line};
  --bk-color-line-strong: ${lineStrong};
  --bk-color-success: #1d9d6a;
  --bk-color-danger: #c64d4d;

  /* ---------- Typography ---------- */
  --bk-font-heading: ${heading};
  --bk-font-body: ${body};
  --bk-font-size-xs: 12px;
  --bk-font-size-sm: 14px;
  --bk-font-size-base: 16px;
  --bk-font-size-lg: 18px;
  --bk-font-size-xl: 22px;
  --bk-font-size-2xl: 28px;
  --bk-font-size-3xl: 36px;
  --bk-font-size-4xl: 48px;
  --bk-font-size-display: clamp(40px, 6vw, 72px);
  --bk-line-tight: 1.1;
  --bk-line-body: ${density.line};

  /* ---------- Radius ---------- */
  --bk-radius-sm: ${radii.sm};
  --bk-radius-md: ${radii.md};
  --bk-radius-lg: ${radii.lg};
  --bk-radius-pill: ${radii.pill};

  /* ---------- Spacing ---------- */
  --bk-space-1: ${space[0]};
  --bk-space-2: ${space[1]};
  --bk-space-3: ${space[2]};
  --bk-space-4: ${space[3]};
  --bk-space-5: ${space[4]};
  --bk-space-6: ${space[5]};
  --bk-space-7: ${space[6]};
  --bk-space-8: ${space[7]};
  --bk-space-9: ${space[8]};
  --bk-space-10: ${space[9]};

  /* ---------- Shadows ---------- */
  --bk-shadow-sm: 0 1px 2px rgba(0,0,0,.06), 0 1px 1px rgba(0,0,0,.04);
  --bk-shadow-md: 0 8px 24px -10px rgba(0,0,0,.18), 0 2px 6px rgba(0,0,0,.06);
  --bk-shadow-lg: 0 30px 60px -24px rgba(0,0,0,.28);

  /* ---------- Layout ---------- */
  --bk-content-width: 720px;
  --bk-page-width: 1200px;
}
${dark_}
/* ---------- Base ---------- */
.bk-theme {
  background: var(--bk-color-surface);
  color: var(--bk-color-ink);
  font-family: var(--bk-font-body);
  font-size: var(--bk-font-size-base);
  line-height: var(--bk-line-body);
  -webkit-font-smoothing: antialiased;
}
.bk-theme *,
.bk-theme *::before,
.bk-theme *::after { box-sizing: border-box; }

.bk-theme h1, .bk-theme h2, .bk-theme h3, .bk-theme h4 {
  font-family: var(--bk-font-heading);
  line-height: var(--bk-line-tight);
  letter-spacing: -0.02em;
  margin: 0;
  color: var(--bk-color-ink);
}
.bk-theme p { margin: 0 0 var(--bk-space-4); }
.bk-theme a { color: var(--bk-color-primary-strong); text-underline-offset: 3px; }
.bk-theme a:hover { text-decoration-thickness: 2px; }

/* ---------- Header ---------- */
.bk-header {
  position: sticky; top: 0; z-index: 50;
  background: color-mix(in srgb, var(--bk-color-surface) 92%, transparent);
  backdrop-filter: saturate(160%) blur(12px);
  border-bottom: 1px solid var(--bk-color-line);
}
.bk-header__inner {
  max-width: var(--bk-page-width);
  margin: 0 auto;
  display: flex;
  align-items: center;
  gap: var(--bk-space-6);
  padding: var(--bk-space-4) var(--bk-space-6);
}
.bk-logo {
  display: inline-flex;
  align-items: center;
  gap: var(--bk-space-3);
  font-family: var(--bk-font-heading);
  font-weight: 800;
  font-size: var(--bk-font-size-xl);
  letter-spacing: -0.01em;
  color: var(--bk-color-ink);
  text-decoration: none;
}
.bk-logo__mark {
  display: inline-grid;
  place-items: center;
  width: 36px; height: 36px;
  border-radius: var(--bk-radius-md);
  background: linear-gradient(135deg, var(--bk-color-primary), var(--bk-color-accent));
  color: var(--bk-color-on-primary);
  font-weight: 800;
  font-family: var(--bk-font-heading);
}
.bk-nav { display: flex; gap: var(--bk-space-5); flex: 1; }
.bk-nav a {
  font-size: var(--bk-font-size-sm);
  font-weight: 600;
  color: var(--bk-color-ink-muted);
  text-decoration: none;
  padding: var(--bk-space-2) 0;
  border-bottom: 2px solid transparent;
  transition: color .15s ease, border-color .15s ease;
}
.bk-nav a:hover { color: var(--bk-color-ink); border-bottom-color: var(--bk-color-primary); }
.bk-header__cta {
  display: inline-flex;
  align-items: center;
  gap: var(--bk-space-3);
}
.bk-btn {
  display: inline-flex; align-items: center; gap: var(--bk-space-2);
  padding: 10px 16px;
  border-radius: var(--bk-radius-md);
  font-weight: 600;
  font-size: var(--bk-font-size-sm);
  border: 1px solid transparent;
  cursor: pointer;
  text-decoration: none;
  transition: transform .15s ease, background .2s ease, box-shadow .2s ease, color .2s ease;
}
.bk-btn--primary {
  background: var(--bk-color-primary);
  color: var(--bk-color-on-primary);
  box-shadow: 0 4px 14px -4px color-mix(in srgb, var(--bk-color-primary) 60%, transparent);
}
.bk-btn--primary:hover { background: var(--bk-color-primary-strong); }
.bk-btn--ghost {
  background: transparent;
  color: var(--bk-color-ink);
  border-color: var(--bk-color-line-strong);
}
.bk-btn--ghost:hover { background: var(--bk-color-surface-1); }

/* ---------- Article hero ---------- */
.bk-article {
  max-width: var(--bk-page-width);
  margin: 0 auto;
  padding: var(--bk-space-8) var(--bk-space-6);
}
.bk-article__breadcrumbs {
  display: flex;
  gap: var(--bk-space-2);
  align-items: center;
  font-size: var(--bk-font-size-xs);
  color: var(--bk-color-ink-muted);
  text-transform: uppercase;
  letter-spacing: 0.12em;
  margin-bottom: var(--bk-space-4);
}
.bk-tag {
  display: inline-block;
  padding: 4px 10px;
  border-radius: var(--bk-radius-pill);
  background: var(--bk-color-primary);
  color: var(--bk-color-on-primary);
  font-size: var(--bk-font-size-xs);
  font-weight: 700;
  letter-spacing: 0.08em;
  text-transform: uppercase;
}
.bk-tag--accent { background: var(--bk-color-accent); color: var(--bk-color-on-accent); }
.bk-tag--soft   { background: var(--bk-color-primary-soft); color: var(--bk-color-primary-strong); }

.bk-article__title {
  font-size: var(--bk-font-size-display);
  font-weight: 800;
  letter-spacing: -0.025em;
  margin: var(--bk-space-3) 0 var(--bk-space-4);
  max-width: 22ch;
}
.bk-article__deck {
  font-size: var(--bk-font-size-xl);
  line-height: 1.45;
  color: var(--bk-color-ink-muted);
  max-width: var(--bk-content-width);
  margin: 0 0 var(--bk-space-6);
}
.bk-article__byline {
  display: flex;
  align-items: center;
  gap: var(--bk-space-4);
  font-size: var(--bk-font-size-sm);
  color: var(--bk-color-ink-muted);
  margin-bottom: var(--bk-space-6);
  flex-wrap: wrap;
}
.bk-avatar {
  width: 40px; height: 40px;
  border-radius: var(--bk-radius-pill);
  background: linear-gradient(135deg, var(--bk-color-primary), var(--bk-color-accent));
  display: inline-grid; place-items: center;
  color: var(--bk-color-on-primary);
  font-weight: 700;
  font-family: var(--bk-font-heading);
}
.bk-byline__name { color: var(--bk-color-ink); font-weight: 600; }

.bk-hero {
  position: relative;
  border-radius: var(--bk-radius-lg);
  overflow: hidden;
  aspect-ratio: 16 / 9;
  margin-bottom: var(--bk-space-7);
  background: linear-gradient(135deg, var(--bk-color-primary), var(--bk-color-accent));
}
.bk-hero img { width: 100%; height: 100%; object-fit: cover; display: block; }
.bk-hero__caption {
  position: absolute; left: var(--bk-space-5); bottom: var(--bk-space-4);
  font-size: var(--bk-font-size-xs);
  color: rgba(255,255,255,.92);
  background: rgba(0,0,0,.45);
  padding: 6px 10px;
  border-radius: var(--bk-radius-sm);
  backdrop-filter: blur(6px);
}

/* ---------- Article body ---------- */
.bk-prose {
  max-width: var(--bk-content-width);
  margin: 0 auto;
  font-size: var(--bk-font-size-lg);
  line-height: var(--bk-line-body);
}
.bk-prose p { margin: 0 0 var(--bk-space-5); }
.bk-prose h2 {
  font-size: var(--bk-font-size-2xl);
  margin: var(--bk-space-7) 0 var(--bk-space-4);
}
.bk-prose blockquote {
  margin: var(--bk-space-7) 0;
  padding: var(--bk-space-2) 0 var(--bk-space-2) var(--bk-space-5);
  border-left: 4px solid var(--bk-color-primary);
  font-family: var(--bk-font-heading);
  font-size: var(--bk-font-size-2xl);
  line-height: 1.3;
  color: var(--bk-color-ink);
  font-style: italic;
}
.bk-prose blockquote cite {
  display: block;
  font-family: var(--bk-font-body);
  font-style: normal;
  font-weight: 600;
  font-size: var(--bk-font-size-sm);
  color: var(--bk-color-ink-muted);
  margin-top: var(--bk-space-2);
}
.bk-prose figure { margin: var(--bk-space-6) 0; }
.bk-prose figure img {
  width: 100%;
  border-radius: var(--bk-radius-lg);
  display: block;
}
.bk-prose figcaption {
  font-size: var(--bk-font-size-sm);
  color: var(--bk-color-ink-muted);
  margin-top: var(--bk-space-2);
}
.bk-prose a { color: var(--bk-color-primary-strong); font-weight: 500; }

.bk-pull {
  margin: var(--bk-space-7) auto;
  padding: var(--bk-space-6);
  background: var(--bk-color-primary-soft);
  border-left: 6px solid var(--bk-color-primary);
  border-radius: var(--bk-radius-md);
  max-width: var(--bk-content-width);
}
.bk-pull p {
  font-family: var(--bk-font-heading);
  font-size: var(--bk-font-size-2xl);
  line-height: 1.25;
  color: var(--bk-color-ink);
  margin: 0;
}

/* ---------- New feed experience ---------- */
.bk-feed {
  background: var(--bk-color-surface-1);
  border-top: 1px solid var(--bk-color-line);
  padding: var(--bk-space-9) var(--bk-space-6);
  margin-top: var(--bk-space-9);
}
.bk-feed__inner {
  max-width: var(--bk-page-width);
  margin: 0 auto;
}
.bk-feed__head {
  display: flex;
  align-items: flex-end;
  justify-content: space-between;
  gap: var(--bk-space-5);
  margin-bottom: var(--bk-space-6);
  flex-wrap: wrap;
}
.bk-feed__title {
  font-size: var(--bk-font-size-3xl);
  font-weight: 800;
  letter-spacing: -0.02em;
}
.bk-feed__sub {
  color: var(--bk-color-ink-muted);
  margin-top: var(--bk-space-2);
  font-size: var(--bk-font-size-base);
}
.bk-feed__filters {
  display: flex; gap: var(--bk-space-2); flex-wrap: wrap;
}
.bk-filter {
  padding: 8px 14px;
  border-radius: var(--bk-radius-pill);
  background: transparent;
  border: 1px solid var(--bk-color-line-strong);
  color: var(--bk-color-ink-muted);
  font-size: var(--bk-font-size-sm);
  font-weight: 500;
  cursor: pointer;
  transition: all .15s ease;
}
.bk-filter:hover { color: var(--bk-color-ink); border-color: var(--bk-color-primary); }
.bk-filter[aria-pressed="true"] {
  background: var(--bk-color-primary);
  border-color: var(--bk-color-primary);
  color: var(--bk-color-on-primary);
}

.bk-feed__grid {
  display: grid;
  gap: var(--bk-space-6);
  grid-template-columns: 2fr 1fr 1fr;
  grid-template-rows: auto auto;
  grid-template-areas:
    "lead side1 side2"
    "lead side3 side4"
    "card1 card2 card3";
}
@media (max-width: 980px) {
  .bk-feed__grid {
    grid-template-columns: 1fr 1fr;
    grid-template-areas:
      "lead lead"
      "side1 side2"
      "side3 side4"
      "card1 card2"
      "card3 card3";
  }
}
@media (max-width: 640px) {
  .bk-feed__grid {
    grid-template-columns: 1fr;
    grid-template-areas:
      "lead"
      "side1"
      "side2"
      "side3"
      "side4"
      "card1"
      "card2"
      "card3";
  }
}
.bk-card {
  display: flex;
  flex-direction: column;
  background: var(--bk-color-surface);
  border: 1px solid var(--bk-color-line);
  border-radius: var(--bk-radius-lg);
  overflow: hidden;
  text-decoration: none;
  color: inherit;
  transition: transform .25s ease, box-shadow .25s ease, border-color .2s ease;
}
.bk-card:hover {
  transform: translateY(-4px);
  border-color: var(--bk-color-primary-soft);
  box-shadow: var(--bk-shadow-md);
}
.bk-card__media {
  aspect-ratio: 16 / 10;
  background: linear-gradient(135deg, var(--bk-color-primary), var(--bk-color-accent));
  position: relative;
}
.bk-card__media img { width: 100%; height: 100%; object-fit: cover; display: block; }
.bk-card__category {
  position: absolute;
  left: var(--bk-space-3);
  top: var(--bk-space-3);
  background: var(--bk-color-surface);
  color: var(--bk-color-primary-strong);
  font-size: var(--bk-font-size-xs);
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  padding: 4px 10px;
  border-radius: var(--bk-radius-pill);
}
.bk-card__body { padding: var(--bk-space-5); display: flex; flex-direction: column; gap: var(--bk-space-2); flex: 1; }
.bk-card__title {
  font-family: var(--bk-font-heading);
  font-size: var(--bk-font-size-xl);
  font-weight: 700;
  line-height: 1.2;
  letter-spacing: -0.01em;
  color: var(--bk-color-ink);
}
.bk-card__deck {
  color: var(--bk-color-ink-muted);
  font-size: var(--bk-font-size-sm);
  line-height: 1.5;
}
.bk-card__meta {
  margin-top: auto;
  font-size: var(--bk-font-size-xs);
  color: var(--bk-color-ink-muted);
  display: flex;
  gap: var(--bk-space-3);
  align-items: center;
}
.bk-card--lead { grid-area: lead; }
.bk-card--lead .bk-card__media { aspect-ratio: 16 / 11; }
.bk-card--lead .bk-card__title { font-size: var(--bk-font-size-3xl); }
.bk-card--lead .bk-card__deck { font-size: var(--bk-font-size-base); }

.bk-card--row {
  display: grid;
  grid-template-columns: 110px 1fr;
}
.bk-card--row .bk-card__media { aspect-ratio: 1 / 1; }
.bk-card--row .bk-card__title { font-size: var(--bk-font-size-base); }
.bk-card--row .bk-card__body { padding: var(--bk-space-3) var(--bk-space-4); gap: var(--bk-space-1); }
.bk-card--row .bk-card__category { display: none; }
.bk-card--row .bk-card__deck { display: none; }

/* ---------- Newsletter strip ---------- */
.bk-newsletter {
  background: var(--bk-color-ink);
  color: var(--bk-color-surface);
  padding: var(--bk-space-9) var(--bk-space-6);
  text-align: center;
}
.bk-newsletter__inner {
  max-width: 640px;
  margin: 0 auto;
}
.bk-newsletter h2 {
  color: var(--bk-color-surface);
  font-size: var(--bk-font-size-3xl);
  margin-bottom: var(--bk-space-3);
}
.bk-newsletter p { color: color-mix(in srgb, var(--bk-color-surface) 70%, transparent); margin-bottom: var(--bk-space-5); }
.bk-newsletter form {
  display: flex; gap: var(--bk-space-3);
  max-width: 480px; margin: 0 auto;
}
.bk-newsletter input {
  flex: 1;
  padding: 12px 16px;
  border-radius: var(--bk-radius-md);
  border: 1px solid color-mix(in srgb, var(--bk-color-surface) 25%, transparent);
  background: color-mix(in srgb, var(--bk-color-surface) 8%, transparent);
  color: var(--bk-color-surface);
  font: inherit;
}
.bk-newsletter input::placeholder { color: color-mix(in srgb, var(--bk-color-surface) 50%, transparent); }
.bk-newsletter input:focus { outline: 2px solid var(--bk-color-accent); outline-offset: 1px; }
.bk-newsletter .bk-btn--primary { background: var(--bk-color-accent); color: var(--bk-color-on-accent); }

/* ---------- Footer ---------- */
.bk-footer {
  padding: var(--bk-space-7) var(--bk-space-6) var(--bk-space-6);
  background: var(--bk-color-surface);
  border-top: 1px solid var(--bk-color-line);
  font-size: var(--bk-font-size-sm);
  color: var(--bk-color-ink-muted);
}
.bk-footer__inner {
  max-width: var(--bk-page-width);
  margin: 0 auto;
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  gap: var(--bk-space-5);
}
.bk-footer a { color: var(--bk-color-ink-muted); text-decoration: none; margin-right: var(--bk-space-4); }
.bk-footer a:hover { color: var(--bk-color-ink); }

/* ---------- Reading progress ---------- */
.bk-progress {
  position: fixed; top: 0; left: 0; right: 0;
  height: 3px;
  background: transparent;
  z-index: 60;
}
.bk-progress__bar {
  height: 100%;
  width: 0%;
  background: linear-gradient(90deg, var(--bk-color-primary), var(--bk-color-accent));
  transition: width .1s linear;
}
`;
}
